// Generated by CoffeeScript 1.9.3
(function() {
  var app, express, mongoose, port, router;

  express = require("express");

  mongoose = require("mongoose");

  app = express();

  port = process.env.PORT || 3000;

  router = express.Router();

  router.get('/', function(req, res) {
    res.json({
      message: "Hello Coffee!"
    });
  });

  app.use('/api', router);

  app.listen(port);

  console.log("Running server on port: " + port);

}).call(this);

//# sourceMappingURL=server.js.map
