# Generated by CoffeeScript 1.9.3
UserSchema = undefined
bcrypt = undefined
mongoose = undefined
mongoose = require('mongoose')
bcrypt = require('bcrypt-nodejs')

UserSchema = new (mongoose.Schema)(
  email:
    type: String
    unique: true
    required: true
  password:
    type: String
    required: true)

UserSchema.pre 'save', (callback) ->
  user = this
  if !user.isModified('password')
    return callback()
  bcrypt.genSalt 5, (err, salt) ->
    if err
      return callback(err)
    bcrypt.hash user.password, salt, null, (err, hash) ->
      if err
        return callback(err)
      user.password = hash
      callback()


UserSchema.methods.verifyPassword = (password, cb) ->
  bcrypt.compare password, @password, (err, isMatch) ->
    if err
      return cb(err)
    cb null, isMatch


module.exports = mongoose.model('User', UserSchema)
## sourceMappingURL=user.js.map
